import axios from "axios";
import { IMonitorJobData, MonitorHandlerFn } from "../Types/monitor.types";

export const handleWebsiteMonitor: MonitorHandlerFn = async (data) => {
  const { url, check_status, keywords } = data;

  const rawUrl = data.url;
  const turl = rawUrl?.trim();
  console.log("raw url:", JSON.stringify(rawUrl));
  console.log("trimmed url:", JSON.stringify(turl));

  const response = await axios.get(url!, {
    timeout: 15000,
    validateStatus: () => true,
    headers: {
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Accept-Language": "en-US,en;q=0.9",
    },
    maxRedirects: 5,
  });

  // const response = await axios.get(url!, {
  //   timeout: 15000,
  //   validateStatus: () => true,
  //   responseType: "text",
  //   transformResponse: [(data: IMonitorJobData) => data],
  //   maxRedirects: 5,
  //   // no custom headers for now
  // });

  // console.log(response);

  if (check_status && (response.status < 200 || response.status >= 300)) {
    throw new Error(`HTTP Status ${response.status}`);
  }

  if (keywords && keywords.length > 0) {
    const body =
      typeof response.data === "string"
        ? response.data
        : JSON.stringify(response.data);

    const lower = body.toLowerCase();

    if (
      lower.includes("generated by cloudfront") ||
      lower.includes("the request could not be satisfied") ||
      lower.includes("just a moment...") ||
      lower.includes("enable javascript and cookies to continue") ||
      lower.includes("/cdn-cgi/challenge-platform/")
    ) {
      throw new Error("Blocked or served CDN/challenge error page");
    }

    const missing = keywords.filter((word) => !body.includes(word));
    if (missing.length > 0) {
      throw new Error(`Missing keywords: ${missing.join(", ")}`);
    }
  }
};
